name: Build

on:
  pull_request:
    branches: ['main']

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        go-version: ['1.19', '1.20']
    name: Build ${{ matrix.go-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - uses: golang/govulncheck-action@dd3ead030e4f2cf713062f7a3395191802364e13 # v1

      - run: |
          go build ./...
          go test -run=^$ ./...
