name: Basic e2e test

on:
  pull_request: 
    branches: ['main']

jobs:
  e2e:
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubuntu-latest
        - windows-latest
    name: e2e ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - name: Build and run ko container
      env:
        KO_DOCKER_REPO: ko.local
      shell: bash
      run: |
        set -euxo pipefail

        # eval `go env`, compatible with Windows and Linux
        # cribbed from https://gist.github.com/Syeberman/39d81b1e17d091be5657ecd6fbff0753
        eval $(go env | sed -r 's/^(set )?(\w+)=("?)(.*)\3$/\2="\4"/gm')

        if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
          # Select the Windows image for 10.0.17763.2300 specifically, to match
          # the GitHub Actions Windows runner environment that will run the
          # image later.
          cat > .ko.yaml << EOF
          baseImageOverrides:
            github.com/google/ko: golang:1.17@sha256:1e646169ec55ead497d3bc74e19e1a3d905682d188ae3cda0adae9e3f8724ffc
          EOF
        fi

        echo platform is ${GOOS}/${GOARCH}
        # Build and run the ko binary, which should be runnable.
        docker run $(go run ./ publish ./ --platform=${GOOS}/${GOARCH} --preserve-import-paths) version

        # Build and run the test/ binary, which should log "Hello there" served from KO_DATA_PATH
        testimg=$(go run ./ publish ./test --platform=${GOOS}/${GOARCH} --preserve-import-paths)
        docker run ${testimg} --wait=false 2>&1 | grep "Hello there"

        # Check that symlinks in kodata are chased.
        # Skip this test on Windows.
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          docker run ${testimg} --wait=false -f HEAD
        fi

        # Check that using ldflags to set variables works.
        cat >> .ko.yaml << EOF

        builds:
        - id: test
          main: ./test/
          ldflags:
          - "-X main.version=${{ github.sha }}"
        EOF
        docker run $(go run ./ publish ./test/ --platform=${GOOS}/${GOARCH}) --wait=false 2>&1 | grep "${{ github.sha }}"

