name: Integration Test

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Module Tests
    strategy:
      matrix:
        go-version:
          - '1.20'
          - '1.21'

    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true

      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

      - env:
          GOPATH: does not matter
        run: ./integration_test.sh
