name: Push to quay.io

on:
  pull_request_target:
    branches: ['main']
  push:
    branches: ['main']
  workload_dispatch:

jobs:
  quay:
    name: Push to quay.io
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
        check-latest: true
    - env:
        QUAY_USERNAME: ko-testing
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        KO_DOCKER_REPO: quay.io/ko-testing/test
      run: |
        echo ${QUAY_PASSWORD} | go run ./ login --username=${QUAY_USERNAME} --password-stdin quay.io
        go run ./ build --platform=all ./test/

