name: Verify

on:
  pull_request:
    branches: ['main']

jobs:
  verify:
    name: Verify Codegen
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - uses: actions/checkout@v2
    - name: Verify
      run: ./hack/presubmit.sh
